# Don't do anything if this is not an interactive session
case $- in
    *i*) ;;
      *) return;;
esac

# Enable tab-completion
[[ -f /etc/bash_completion ]] && source /etc/bash_completion

# Append to history file instead of overwriting
shopt -s histappend

# Don't add duplicate lines, or lines starting with a space to the history file
HISTCONTROL=ignoreboth

# Set number of commands stored in memory and in the history file
HISTSIZE=10000
HISTFILESIZE=10000
HISTFILE=$HOME/.history_bash

# Update values of LINES and COLUMNS after window resize
shopt -s checkwinsize

# Use '**' in pathname expansions like in ZSH
shopt -s globstar

# Set prompt
PS1='\[\e[1;33m\]\W \$\[\e[0m\] '

# Add function to switch to a verbose prompt
prompt-verbose() {
    PS1='\n\[\e[1;32m\]\u@\h:\[\e[0m\]\w \[\e[1;34m\][\T] \n\[\e[1;33m\]\$ \[\e[0m\]'
}

# Source the `.shell/common` file
[[ -f $HOME/.shell/common ]] && source $HOME/.shell/common
